export enum IPCSignals {
  MAIN_MSG_RECEIVER_REFRESH = 'MAIN_MSG_RECEIVER_REFRESH',
  RENDER_MSG_RECEIVER_REFRESH = 'RENDER_MSG_RECEIVER_REFRESH',
  MAIN_MSG_RECEIVER_SEND_MESSAGE = 'MAIN_MSG_RECEIVER_SEND_MESSAGE',
  RENDER_MSG_RECEIVER_SEND_RESULT = 'RENDER_MSG_RECEIVER_SEND_RESULT',
  MAIN_MSG_RECEIVER_SEND_MESSAGE_STOP = 'MAIN_MSG_RECEIVER_SEND_MESSAGE_STOP',
  RENDER_MSG_RECEIVER_SEND_RESULT_STOPED = 'RENDER_MSG_RECEIVER_SEND_RESULT_STOPED',
}
